<div>Content</div>

<div id="ajax-response-id">sssssss</div>
<?php
$ajaxurl = '';//$block->getAjaxUrl();
?>
<script type="text/x-magento-init">
      /*  {
            "*": {
                "Avadhesh_HelloWorld/js/custom": {
                    "AjaxUrl": "<?php echo $ajaxurl; ?>",
                    "CurrentProduct": "<?php echo $currentProductId; ?>",
                }
            }
        }*/
</script>